# Generated by Django 4.1.7 on 2023-02-26 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone-Number')),
                ('role', models.CharField(choices=[('factory', 'Factory'), ('freight', 'Freight'), ('driver', 'Driver')], default='factory', max_length=10)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('data_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactoryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factories', to=settings.AUTH_USER_MODEL)),
                ('freight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
