# Generated by Django 4.1.7 on 2023-02-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('otp_code', models.CharField(max_length=5)),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
    ]
