# Generated by Django 4.1.7 on 2023-02-26 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
