# Generated by Django 4.1.7 on 2023-02-26 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('postage_date', models.DateField()),
                ('status', models.CharField(choices=[('close', 'Close'), ('open', 'Open')], default='open', max_length=5)),
                ('factory_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for confirmation'), ('valid', 'Valid')], default='waiting', max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bars_driver', to=settings.AUTH_USER_MODEL)),
                ('freight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bars_freight', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bars_product', to='products.product')),
            ],
        ),
    ]
